//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ctyppsachmvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctpx
    {
        public int idpx { get; set; }
        public int idctpx { get; set; }
        public Nullable<int> idsach { get; set; }
        public Nullable<int> soluong { get; set; }
    
        public virtual phieuxuat phieuxuat { get; set; }
        public virtual sach sach { get; set; }
    }
}
