//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ctyppsachmvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ctyppsachEntities : DbContext
    {
        public ctyppsachEntities()
            : base("name=ctyppsachEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<congnotheothoigian> congnotheothoigian { get; set; }
        public virtual DbSet<ctdmsdb> ctdmsdb { get; set; }
        public virtual DbSet<ctpn> ctpn { get; set; }
        public virtual DbSet<ctpx> ctpx { get; set; }
        public virtual DbSet<daily> daily { get; set; }
        public virtual DbSet<danhmucsachdaban> danhmucsachdaban { get; set; }
        public virtual DbSet<hangtoncuadaily> hangtoncuadaily { get; set; }
        public virtual DbSet<linhvuc> linhvuc { get; set; }
        public virtual DbSet<nxb> nxb { get; set; }
        public virtual DbSet<phieunhap> phieunhap { get; set; }
        public virtual DbSet<phieutratien> phieutratien { get; set; }
        public virtual DbSet<phieuxuat> phieuxuat { get; set; }
        public virtual DbSet<sach> sach { get; set; }
        public virtual DbSet<sotienphaitrachonxb> sotienphaitrachonxb { get; set; }
        public virtual DbSet<tonkho> tonkho { get; set; }
    }
}
