//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ctyppsachmvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class danhmucsachdaban
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public danhmucsachdaban()
        {
            this.ctdmsdb = new HashSet<ctdmsdb>();
        }
    
        public int iddmsdb { get; set; }
        public Nullable<int> iddl { get; set; }
        public Nullable<System.DateTime> thoigian { get; set; }
        public Nullable<decimal> sotiendathanhtoan { get; set; }
        public Nullable<decimal> sotienconno { get; set; }
        public string tinhtrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ctdmsdb> ctdmsdb { get; set; }
        public virtual daily daily { get; set; }
    }
}
