//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ctyppsachmvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phieutratien
    {
        public int idptt { get; set; }
        public Nullable<int> idnxb { get; set; }
        public Nullable<decimal> sotientra { get; set; }
        public string tinhtrang { get; set; }
        public Nullable<System.DateTime> ngaytaophieu { get; set; }
    
        public virtual nxb nxb { get; set; }
    }
}
