//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ctyppsachmvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phieunhap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public phieunhap()
        {
            this.ctpn = new HashSet<ctpn>();
        }
    
        public int idpn { get; set; }
        public Nullable<int> idnxb { get; set; }
        public string nguoigiaosach { get; set; }
        public Nullable<System.DateTime> ngaynhap { get; set; }
        public string nguoivietphieu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ctpn> ctpn { get; set; }
        public virtual nxb nxb { get; set; }
    }
}
