//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ctyppsachmvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sach()
        {
            this.ctdmsdb = new HashSet<ctdmsdb>();
            this.ctpn = new HashSet<ctpn>();
            this.ctpx = new HashSet<ctpx>();
            this.hangtoncuadaily = new HashSet<hangtoncuadaily>();
            this.tonkho = new HashSet<tonkho>();
        }
    
        public int idsach { get; set; }
        public string tensach { get; set; }
        public string tacgia { get; set; }
        public Nullable<int> idnxb { get; set; }
        public Nullable<int> idlv { get; set; }
        public Nullable<decimal> giaxuat { get; set; }
        public Nullable<decimal> gianhap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ctdmsdb> ctdmsdb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ctpn> ctpn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ctpx> ctpx { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hangtoncuadaily> hangtoncuadaily { get; set; }
        public virtual linhvuc linhvuc { get; set; }
        public virtual nxb nxb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tonkho> tonkho { get; set; }
    }
}
