//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ctyppsachmvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tonkho
    {
        public int idtk { get; set; }
        public int idsach { get; set; }
        public System.DateTime thoidiem { get; set; }
        public Nullable<int> soluongton { get; set; }
        public Nullable<int> idphieu { get; set; }
    
        public virtual sach sach { get; set; }
    }
}
